#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias cls='clear'
alias ll='ls -lh --color=auto'
alias fm='GTK_IM_MODULE=fcitx nautilus .'

PS1='\[\033[0;32m\][\u@\h \w]\$\[\033[0m\] '

if [[ ! -v NIRI_RUNNING ]]; then
  export NIRI_RUNNING=1
  niri-session 2>/dev/null
fi
